apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: negi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AkashiyaSanta/argo.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: negi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-operator
  template:
    metadata:
      labels:
        app: k6-operator
    spec:
      containers:
        - name: k6-operator
          image: ghcr.io/grafana/k6-operator:latest
          ports:
            - containerPort: 8080
