apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomizedapplication
  namespace: argocd
spec:
  source:
    project: negi
    repoURL: https://github.com/AkashiyaSanta/argo.git
    targetRevision: main
    path: customizedspec
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: negi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
