apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: negi
spec:
  project: default
  source:
    repoURL: 'https://github.com/AkashiyaSanta/argo.git'
    targetRevision: HEAD
    path: .  # Directory where child app manifests are stored
  destination:
    server: https://kubernetes.default.svc
    namespace: negi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
