apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
